### ISSUE TITLE
Dokumenter hvordan hvert krav er løst

### ISSUE THREAD

**Issue by dliso** [IT2810/it2810-webutvikling-h17-prosjekt-4-group-23#7]

**Comment by Desember29** [comment]
Hvis noen leser igjennom og ser over svarene jeg har skrevet på README.md angående hvordan vi har løst kravene, så er det egentlig bare to punkter som gjerne burde bli sett på. Det er:

- I webappliksjonen skal det inngå en backend database som kjøres på gruppas virtuelle maskin. Type database og hvordan denne brukes er opp til dere å bestemme, men grensesnittet til databasen skal være godt designet ihht. god praksis (bruk av REST ea).

- Webapplisjonen må implementere "session"-håndtering (som du f.eks. trenger for å implementere dynamisk lasting, min side, og filtrering/sortering som skal fungere med sidevisning).
